### ISSUE TITLE
report_xlsx module is required

### ISSUE THREAD

**Issue by shahzebkhan111** [odoomates/Development-Tutorials#1]
I have downloaded the module and when I try to install the module, I am getting the following error.

You try to install module 'om_hospital' that depends on module 'report_xlsx'.
But the latter module is not available in your system.

I have searched my app list and I didn't find any report_xlsx module.

**Comment by odoomates** [comment]
Hi,
Download the dependent module from here: https://apps.odoo.com/apps/modules/12.0/report_xlsx/

Thanks
