### ISSUE TITLE
kanban draggable Module Missing

### ISSUE THREAD

**Issue by nickchacha** [odoomates/Development-Tutorials#3]
Hi Team, 
Couldn't locate the above required module. Please share the source if available

Thanks

**Comment by setuconsulting** [comment]
i am facing same issue. no module: kanban_draggable

**Comment by ashishsetu** [comment]
I am facing the same issue. no module: kanban_draggable

**Comment by odoomates** [comment]
Hi, You can get it from: https://apps.odoo.com/apps/modules/11.0/kanban_draggable/
